### ISSUE TITLE
Example of differing method schemas

### ISSUE THREAD

**Issue by ndarilek** [MangroveTech/koa-scheme#2]
This looks like exactly what I'm looking for, and I've got it quickly up and running validating incoming requests.

I'm uncertain about something, though. Say I have an /api/session endpoint. POSTing should require login/password parameters, but DELETE requires none and logs out. How do I model this? It looks like API endpoints are keyed first on path, then on request/response. Seems like it'd make sense to key on path, then method, then request/response. But perhaps I'm missing something.

**Comment by nswbmw** [comment]
@ndarilek  @yorkie koa-scheme v1.0.0 released, it has some fancy features. checkout～

**Comment by yorkie** [comment]
neat!! :cherries:
